# === Пример конфигурации для симулятора "Мафия" ===

# Базовые параметры
n_players: 9
seed: 42                   # фиксированный сид => детерминированные результаты
human: false               # интерактивный игрок отключён
log: full                  # подробный лог в консоль
open_announcements: false  # без «открытых» объявлений
logs_dir: logs             # каталог для round_*.txt и summary.txt
tie: none                  # политика ничьей днём: none|random
k_mafia_div: 3             # делитель для подсчёта числа мафии (>=1)

# Дополнительные роли (из ТЗ)
executioner_count: 1       # Палач (0 или 1)
journalist_count: 1        # Журналист (0 или 1)
eavesdropper_count: 1      # Ушастик (0 или 1)

# Режим движка:
#   engine: coro    => использовать кооперативный движок на корутинах
#   engine: threads => классический движок на потоках (std::jthread + barriers)
engine: coro
# Альтернативно можно задать булевым ключом:
# use_coroutines: true
