# Любой из ключей можно опустить — тогда будет взято значение по умолчанию.

# --- Общие параметры ---
n_players: 9            # количество игроков (>= 5 разумно)
seed: 42                # 0 => случайная инициализация ГПСЧ
human: false            # true — один игрок будет интерактивным ( --human )
log: full               # short | full  — подробность консольного лога
open: false             # true — "открытые" объявления (видно роли/цели в логах)
logs_dir: logs          # каталог для файлов round_*.txt и summary.txt

# Политика ничьей днём: none — никто не казнён; random — случайный из лидеров
tie: none               # none | random

# Формула числа мафии: mafia_cnt = max(1, n_players / max(3, k_mafia_div))
k_mafia_div: 3

# --- Дополнительные роли из ТЗ (включены 3 самые простые для реализации) ---
# Разрешены значения 0 или 1 для каждой роли.
executioner_count: 1    # Палач — действует только при дневной ничьей
journalist_count: 1     # Журналист — сравнивает статусы двух игроков ночью
eavesdropper_count: 1   # Ушастик — подслушивает действия на выбранной цели ночью
